### ISSUE TITLE
Error Reading files in Excel Worksheet 97-2003 File - xls format

### ISSUE THREAD

**Issue by rbharathkumar** [crealytics/spark-excel#388] opened 2021-06-25 10:54 UTC
Hi Team, 
I am currently facing an odd error when trying to read xls file using the spark-excel library.

1. The source excel file is an xls - 97-2003 file format.
2. The file has only one sheet with around 200 odd columns and 40k records.
3. With only the basic options set, the file read is successful but takes around 40 to 45 mins.
4. But with the option - 

# Working - Takes 45+ mins to process
``` scala
df_src = spark.read
  .format("com.crealytics.spark.excel")
  .option("dataAddress", "0!A1")
  .option("header", "true")
  .option("treatEmptyValuesAsNulls", "true")
  .option("setErrorCellsToFallbackValues","true")
  .option("usePlainNumberFormat","true")
  .option("inferSchema", "false")
  .schema(source_schema)
  .load(source_file_oath + source_file_name)
```
# Not Working with maxRowsInMemory option
``` scala
df_src = spark.read
  .format("com.crealytics.spark.excel")
  .option("dataAddress", "0!A1")
  .option("header", "true")
  .option("treatEmptyValuesAsNulls", "true")
  .option("setErrorCellsToFallbackValues","true")
  .option("usePlainNumberFormat","true")
  .option("inferSchema", "false")
  .option("maxRowsInMemory", 100)
  .schema(source_schema)
  .load(source_file_oath + source_file_name)
```

# Error Messge:
shadeio.poi.openxml4j.exceptions.OLE2NotOfficeXmlFileException: The supplied data appears to be in the OLE2 Format. You are calling the part of POI that deals with OOXML (Office Open XML) Documents. You need to call a different part of POI to process this data (eg HSSF instead of XSSF)

## Context
> Trying to bring down the time taken to read a large excel file about - 48 MB from 40+ minutes to a lower time frame.

## Your Environment
> Databricks Environment - LTS Run time 
* Spark version: 3.0.1
* Language: Scala
* Spark-Excel version: com.crealytics:spark-excel_2.12:0.13.7
* Operating System and version, cluster environment, ...: Ubuntu - Databricks LTS runtime with sufficient memory and disk space.

#62  Look similar - but it is in closed state and no work arounds apart from removing the maxRowsInMemory option.

**Comment by nightscape** [comment] 2021-06-25 15:25
Hi @rbharathkumar,

This has nothing to do with `maxRowsInMemory`.
spark-excel does not support `.xls` files, and there are no plans from my side to do so...
You could check if you can batch convert the `.xls` files to `.xlsx` files.
Otherwise, you would need to create a PR against this project adding the required functionality.

**Comment by rbharathkumar** [comment] 2021-06-26 03:53
Thank you so much for your quick response.
I am quite surprised to learn that spark-excel does not support `.xls` files. 
It is not mentioned anywhere in the landing page. Maybe I have missed it somewhere.
The main reason I am surprised is that I have used spark-excel to read 3 to 4 `.xls` files for my personal use with exactly the same options mentioned above (working ones) and the read process was _flawless and extremely quick_. Even with the large 50 mb `.xls` the read process was successful but was taking way too much (40min+). 

Can you please help with the below items ?
1. Is it confirmed that spark-excel does not support `.xls` files ? 
2. Would you recommend modifying my existing scripts where I am reading xls files using spark-excel or is it safe to keep them as it is ?
3. Can you please recommend from your experience a good program to batch convert `.xls` files to `.xlsx` files ?
4. Would be nice to have the information about `.xls` file compatibility in the README file.

Thank you for all your efforts in maintaining  spark-excel. It truly is a wonderful program.

**Comment by quanghgx** [comment] 2021-06-27 16:38
Hi @rbharathkumar , please help share your excel file (if it is possible) or utilize some data-generator that can reproduce your performance issue (40min+).
Frankly, I don't know if we can do anything about this, but I am sure will try and report back to you two.
Sincerely,

**Comment by rbharathkumar** [comment] 2021-06-28 14:33
Thank you for your response.
Unfortunately I will not be able to share the source file.
But I did try an excel generator to generate an excel with 199 column and 40000 records in it.
Unfortunately though, the generator could only generate continuous values with no blanks or formatting or so...When I consumed that excel the run was blazing fast - it completed in 5 minutes..

I also created a small piece of code to see where the  script is taking time. Basically just printing the current timestamp before the start of each process. I had 3 steps.
1. Read Excel to Dataframe. - I think this does lazy load - so very quick.
2. Get count of Dataframe.
3. Write to ADLS.

I even tried it with different cluster configs.

**With 4 Partitions:**
Initialization completed at 2021-06-28 13:24:10.619 UTC
Dataframe loaded at 2021-06-28 13:24:10.816 UTC		`- 197 ms`
Count Displayed at 2021-06-28 13:35:09.232 UTC			`- 10 minutes and 59 seconds`
Completed writing at 2021-06-28 13:58:33.914 UTC		`- 23 minutes and 24 seconds`

**With 8 Partitions:**
Initialization completed at 2021-06-28 11:50:43.339 UTC
Dataframe loaded at 2021-06-28 11:50:43.604 UTC		`- 265 ms`
Count Displayed at 2021-06-28 12:01:37.564 UTC			`- 10 minutes and 54 seconds`
Completed writing at 2021-06-28 12:24:53.161 UTC		`- 23 minutes and 16 seconds`

**With 16 Partitions:**
Initialization completed at 2021-06-28 12:30:56.473 UTC
Dataframe loaded at 2021-06-28 12:30:56.678 UTC		`- 205 ms`
Count Displayed at 2021-06-28 12:41:55.601 UTC			`- 10 minutes and 59 seconds`
Completed writing at 2021-06-28 13:05:14.458 UTC		`- 23 minutes and 19 seconds`

Not sure how to proceed though...

**Comment by quanghgx** [comment] 2021-06-28 16:52
Hi @rbharathkumar 
appreciate your detailed issue description and also sharing your evaluation result.
* spark-excel does support .xls, however in streaming-mode, which it triggered by setting maxRowsInMemory, it does not due to underlining [library](https://github.com/pjfanning/excel-streaming-reader)
* agree, 
   * on (step 1) spark dataframe API is lazy in its natural until some action.
   * step 2 and 3, no difference in runtime because, with single input file, and there is not practical way of splitting and excel file, and the computing is minor (.count), writing to single file (by now), so more threads/more partitions for spark-cluster made no difference. 

To be honest, I have no idea now. Still seeking for large input file or set of files to evaluate reading performance & memory usage.

Thank you rbharathkumar.

**Comment by quanghgx** [comment] 2021-12-05 04:17
Hi @rbharathkumar 

1. Given that https://github.com/crealytics/spark-excel/pull/421 is merged. Thanks to @pjfanning 
2. And from my local testing, spark-excel (V2), resource consumption (memory & CPU) are similar to Apache POI.
Spark-excel, as it runs on Spark with its lazy loading, if we load multiple files, and rows are processed in pipeline, Spark-excel will consume much less than the memory needed for all excel file combined.

I am finding some time to put my test result to here: https://github.com/crealytics/spark-excel/wiki/Examples:-Resource-Usage-and-How-Big-Spark-Excel-Can-Handle%3F so other people can verify the result.

Going to resolve this ticket. Feel free to reopen it.
Thank you so much for your feedback.

**Closed by quanghgx** 2021-12-05 04:17 UTC
