### ISSUE TITLE
Dependency issues with Spark's built-in commons-compress

### ISSUE THREAD

**Issue by jwooden1** [crealytics/spark-excel#93] opened 2018-10-26 00:05 UTC
I can use the library when I run spark on my local windows machine and read excel files on the same machine. However, when I upload the files to WASB on Azure and use HDInsight cluster for running spark jobs (either local or cluster mode), I get the following error: 

`java.lang.IllegalArgumentException: InputStream of class class org.apache.commons.compress.archivers.zip.ZipArchiveInputStream is not implementing InputStreamStatistics.
  at org.apache.poi.openxml4j.util.ZipArchiveThresholdInputStream.<init>(ZipArchiveThresholdInputStream.java:63)
  at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipStream(ZipHelper.java:180)
  at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:104)
  at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:298)
  at org.apache.poi.xssf.usermodel.XSSFWorkbookFactory.createWorkbook(XSSFWorkbookFactory.java:129)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.apache.poi.ss.usermodel.WorkbookFactory.createWorkbook(WorkbookFactory.java:314)
  at org.apache.poi.ss.usermodel.WorkbookFactory.createXSSFWorkbook(WorkbookFactory.java:296)
  at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:214)
  at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:180)
  at com.crealytics.spark.excel.ExcelRelation$$anonfun$openWorkbook$2$$anonfun$apply$4.apply(ExcelRelation.scala:66)
  at com.crealytics.spark.excel.ExcelRelation$$anonfun$openWorkbook$2$$anonfun$apply$4.apply(ExcelRelation.scala:66)
  at scala.Option.fold(Option.scala:158)
  at com.crealytics.spark.excel.ExcelRelation$$anonfun$openWorkbook$2.apply(ExcelRelation.scala:66)
  at com.crealytics.spark.excel.ExcelRelation$$anonfun$openWorkbook$2.apply(ExcelRelation.scala:66)
  at scala.Option.getOrElse(Option.scala:121)
  at com.crealytics.spark.excel.ExcelRelation.openWorkbook(ExcelRelation.scala:64)
  at com.crealytics.spark.excel.ExcelRelation.excerpt$lzycompute(ExcelRelation.scala:71)
  at com.crealytics.spark.excel.ExcelRelation.excerpt(ExcelRelation.scala:70)
  at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:264)
  at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:263)
  at scala.Option.getOrElse(Option.scala:121)
  at com.crealytics.spark.excel.ExcelRelation.inferSchema(ExcelRelation.scala:263)
  at com.crealytics.spark.excel.ExcelRelation.<init>(ExcelRelation.scala:91)
  at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:39)
  at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:14)
  at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:8)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:309)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:156)
  ... 53 elided
`

**Comment by nightscape** [comment] 2018-10-26 09:01
I had the same problem a few days ago, but haven't found a proper solution.
The problem is that Spark comes bundled with a rather outdated version of `commons-compress` and POI needs a newer version. In principle it should be possible to override the JARs bundled with Spark with user-provided ones, but I haven't yet managed to successfully do so.
In case you find a solution, please post it here 👍 
In the mean time, you could try older versions of spark-excel maybe the pre-0.10 versions work with the older version of `commons-compress`.

**Comment by nightscape** [comment] 2018-11-09 22:12
I just released `0.10.1` which shades `commons-compress` and should hopefully fix this problem.
Can you give it a try and tell me if it worked?

**Comment by nightscape** [comment] 2018-11-19 21:46
Just trying [another approach](https://github.com/crealytics/spark-excel/commit/c18b886f62735f35410ac30256727be7be5a7fa5). Can someone check `0.11.0-beta3`?

**Comment by hbenzineb** [comment] 2018-11-23 14:34
@nightscape : it's OK :)
Thanks

**Comment by nightscape** [comment] 2018-11-23 15:53
Ok, then I'll backport this to 0.10 and release 0.11 from the beta version.

**Comment by nightscape** [comment] 2018-11-24 11:14
Fixed in 0.10.2 and 0.11.0-beta3.

**Comment by jwooden1** [comment] 2018-11-26 18:53
fix is working for 0.10.2, but not in 0.11.0-beta3. I get this error in 0.12.0-beta3. 
`scala.MatchError: Map(treatemptyvaluesasnulls -> false, path -> /unique.xlsx, useheader -> true, endcolumn -> 8, inferschema -> true, startcolumn -> 0, sheetname -> input) (of class org.apache.spark.sql.catalyst.util.CaseInsensitiveMap)
  at com.crealytics.spark.excel.DataLocator$.apply(DataLocator.scala:52)
  at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:29)
  at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:18)
  at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:12)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:309)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:156)
  ... 53 elided
`

**Comment by abhishek-bhatt3** [comment] 2019-01-25 09:57
> fix is working for 0.10.2, but not in 0.11.0-beta3. I get this error in 0.11.0-beta3.
> `scala.MatchError: Map(treatemptyvaluesasnulls -> false, path -> /unique.xlsx, useheader -> true, endcolumn -> 8, inferschema -> true, startcolumn -> 0, sheetname -> input) (of class org.apache.spark.sql.catalyst.util.CaseInsensitiveMap) at com.crealytics.spark.excel.DataLocator$.apply(DataLocator.scala:52) at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:29) at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:18) at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:12) at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:309) at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178) at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:156) ... 53 elided `
> Looking at the code, it looks to me it is due to making dataaddress a mandetory filed? what is it anyway? Also, I think it is creating a side-effect, because if I pass null when reading, there is no err in read, but it does not read the specified sheet-- looks that it just read the first sheet.

I am facing the same error in 0.11.0. Any update on this?

**Comment by jagadeesh427** [comment] 2019-05-01 18:02
Exception in thread "main" scala.MatchError: Map(treatemptyvaluesasnulls -> true, location -> hdfs://nameservice1//dev/internal/fair_flatfiles/raw/500a_map_e.xlsx, useheader -> true, inferschema -> true, addcolorcolumns -> false, sheetname -> _500a_map_e) (of class org.apache.spark.sql.catalyst.util.CaseInsensitiveMap)

I am facing above issue.

dependencies used .
<dependency>
            <groupId>com.crealytics</groupId>
            <artifactId>spark-excel_2.10</artifactId>
            <version>0.8.3</version>
        </dependency>
    </dependencies>

can anyone help?

**Comment by jagadeesh427** [comment] 2019-05-03 15:07
solved the issue :

used --packages com.crealytics:spark-excel_2.11:0.10.2

worked fine

**Comment by nightscape** [comment] 2019-06-27 14:46
I can reproduce this locally now. The problem seems to be that despite [shading `org.apache.commons.compress`](https://github.com/crealytics/spark-excel/blob/master/build.sbt#L35) [this line](https://github.com/apache/poi/blob/trunk/src/ooxml/java/org/apache/poi/openxml4j/opc/internal/ZipHelper.java#L178) seems to be calling the constructor of the unshaded `ZipArchiveInputStream`.
Trying to find out what's happening...

**Comment by nightscape** [comment] 2019-06-27 16:30
Not understanding it...
The exception says the following:
```
java.lang.IllegalArgumentException: InputStream of class class org.apache.commons.compress.archivers.zip.ZipArchiveInputStream is not implementing InputStreamStatistics.
  org.apache.poi.openxml4j.util.ZipArchiveThresholdInputStream.<init>(ZipArchiveThresholdInputStream.java:63)
  org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipStream(ZipHelper.java:180)
  org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:104)
  org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:298)
  org.apache.poi.xssf.usermodel.XSSFWorkbookFactory.createWorkbook(XSSFWorkbookFactory.java:129)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.apache.poi.ss.usermodel.WorkbookFactory.createWorkbook(WorkbookFactory.java:314)
  org.apache.poi.ss.usermodel.WorkbookFactory.createXSSFWorkbook(WorkbookFactory.java:296)
  org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:214)
  org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:180)
  com.crealytics.spark.excel.DefaultWorkbookReader.$anonfun$openWorkbook$1(WorkbookReader.scala:42)
```

on the other hand, when I download and unzip the spark-excel JAR and run
```bash
javap -verbose com/crealytics/spark-excel_2.12/0.11.2/org/apache/poi/openxml4j/opc/internal/ZipHelper.class
```
it clearly shows that the above method is using the shaded classes:
```
  public static org.apache.poi.openxml4j.util.ZipArchiveThresholdInputStream openZipStream(java.io.InputStream) throws java.io.IOException;
    descriptor: (Ljava/io/InputStream;)Lorg/apache/poi/openxml4j/util/ZipArchiveThresholdInputStream;
    flags: ACC_PUBLIC, ACC_STATIC
    Code:
      stack=5, locals=2, args_size=1
         0: aload_0
         1: invokestatic  #108                // Method org/apache/poi/poifs/filesystem/FileMagic.prepareToCheckMagic:(Ljava/io/InputStream;)Ljava/io/InputStream;
         4: astore_1
         5: aload_1
         6: invokestatic  #139                // Method verifyZipHeader:(Ljava/io/InputStream;)V
         9: new           #141                // class org/apache/poi/openxml4j/util/ZipArchiveThresholdInputStream
        12: dup
        13: new           #143                // class shadeio/commons/compress/archivers/zip/ZipArchiveInputStream
        16: dup
        17: aload_1
        18: invokespecial #145                // Method shadeio/commons/compress/archivers/zip/ZipArchiveInputStream."<init>":(Ljava/io/InputStream;)V
        21: invokespecial #146                // Method org/apache/poi/openxml4j/util/ZipArchiveThresholdInputStream."<init>":(Ljava/io/InputStream;)V
        24: areturn
```

**Comment by jornfranke** [comment] 2019-06-27 16:49
Maybe some of your dependencies have POI as a dependency and then this dependency does not use the shaded commons-io

**Comment by nightscape** [comment] 2019-07-02 16:06
@jornfranke That was exactly the problem. `spark-excel` itself still adds POI as a dependency (see https://github.com/hammerlab/sbt-parent/issues/32).
I'm now bundling and shading all dependencies that require `commons-io`.

I just released `0.12.0` with this fix (and Scala 2.12 compatibility), it should appear on Maven Central in the next few hours.
Please go ahead and try it.
I'll close this issue until there are reports of the problem occurring again.

**Closed by nightscape** 2019-07-02 16:06 UTC

**Comment by jlscott3** [comment] 2019-07-03 16:05
Confirmed 0.12.0 working in AWS Glue now - thanks for the quick response!

**Comment by ecv-stan** [comment] 2019-07-25 10:05
@jlscott3 hi, do u mind to share how do u get this to work in glue?
do u just add the spark-excel_2.12-0.12.0.jar to Jar lib path in the glue job? do u need to set anything else?
I tried spark-excel_2.12-0.12.0.jar and spark-excel_2.11-0.11.1.jar but both throw error...
thanks in advance.

**Comment by nightscape** [comment] 2019-10-02 23:44
It turns out something went wrong while publishing `spark-excel_2.12-0.12.0.jar`, so that version actually still had this problem.
In case anyone wants to try with Scala 2.12 it should work with spark-excel `0.12.1`.

**Comment by tochandrashekhar** [comment] 2020-07-16 08:12
> @jlscott3 hi, do u mind to share how do u get this to work in glue?
> do u just add the spark-excel_2.12-0.12.0.jar to Jar lib path in the glue job? do u need to set anything else?
> I tried spark-excel_2.12-0.12.0.jar, spark-excel_2.11-0.12.0.jar, spark-excel_2.11-0.11.1.jar but all throw error...
> thanks in advance.
> 
> Update:
> 
> Finally I got it working in AWS glue.
> 
> Below are the jars I used:
> ooxml-schemas-1.4.jar
> poi-4.0.0.jar
> spark-excel_2.11-0.12.0.jar
> xmlbeans-3.1.0.jar
> 
> Hope it helps.

Do we need to import in spark code.. Can you please provide some sample code?

**Comment by xvinosh** [comment] 2020-08-14 14:38
Did anyone get the solution to this problem. I am facing the same problem with the latest version of spark-excel -> 0.13.5

scala> val file = new File("/Users/vinodsharma/Documents/Spark-Excel/People.xlsx")
file: java.io.File = /Users/vinodsharma/Documents/Spark-Excel/People.xlsx

scala> val fIP = new FileInputStream(file)
fIP: java.io.FileInputStream = java.io.FileInputStream@236ec69

scala> val wb = new XSSFWorkbook(fIP)
java.lang.IllegalArgumentException: InputStream of class class org.apache.commons.compress.archivers.zip.ZipArchiveInputStream is not implementing InputStreamStatistics.
  at org.apache.poi.openxml4j.util.ZipArchiveThresholdInputStream.<init>(ZipArchiveThresholdInputStream.java:65)
  at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipStream(ZipHelper.java:178)
  at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:104)
  at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:307)
  at org.apache.poi.ooxml.util.PackageHelper.open(PackageHelper.java:47)
  at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:309)
  ... 51 elided

How to go about changing the classpath for common compress jar: In my case, the version of compress jar is org.apache.commons#commons-compress;1.20

**Comment by nightscape** [comment] 2020-08-14 19:57
You might have to manually exclude commons-compress from the dependencies due to this problem which I don't yet know how to fix: https://github.com/hammerlab/sbt-parent/issues/32

**Comment by xvinosh** [comment] 2020-08-17 17:14
@nightscape :
In my case, I tried all the versions from 0.12.1 to 0.13.5, none worked.
Downloaded the latest version of common compress manually which spark-shell showed as if it has downloaded while launching the spark shell with packages option but actually did not(as I could not find anywhere in the maven repo dir where it said, it’s downloaded)
Version: 1.20
Then explicitly mentioned the jar name in the driver’s classpath as mentioned below:
$ spark-shell --driver-class-path /home/xvinosh/.m2/repository/org/apache/commons/commons-compress/1.20/commons-compress-1.20jar

This worked. Hope it helps other.

**Comment by sjahongir** [comment] 2021-04-18 02:44
@nightscape hi
I tried the 0.9.0 version with spark 2.3.1 (local and cluster mode). It is worked but when I use a large excel file, a spark cannot process it.

Then tried higher versions of your library from 0.10:
- spark can process large file when I use as a local mode
- the following error occurs when I use spark as a cluster (standalone) mode

`Exception in thread "main" java.lang.IllegalArgumentException: InputStream of class class org.apache.commons.compress.archivers.zip.ZipFile$1 is not implementing InputStreamStatistics.
        at org.apache.poi.openxml4j.util.ZipArchiveThresholdInputStream.<init>(ZipArchiveThresholdInputStream.java:63)
        at org.apache.poi.openxml4j.util.ZipSecureFile.getInputStream(ZipSecureFile.java:147)
        at org.apache.poi.openxml4j.util.ZipSecureFile.getInputStream(ZipSecureFile.java:34)
        at org.apache.poi.openxml4j.util.ZipFileZipEntrySource.getInputStream(ZipFileZipEntrySource.java:66)
        at org.apache.poi.openxml4j.opc.ZipPackage.getPartsImpl(ZipPackage.java:258)
        at org.apache.poi.openxml4j.opc.OPCPackage.getParts(OPCPackage.java:725)
        at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:238)
        at etl.io.XlsxReader.open(XlsxReader.scala:135)
        at etl.io.XlsxReader.<init>(XlsxReader.scala:153)
        at etl.connectors.excel.ExcelConnector.readXlsx(ExcelConnector.scala:194)
        at etl.connectors.excel.ExcelConnector.read(ExcelConnector.scala:119)
        at etl.io.DatasetReader$.read(DatasetReader.scala:47)
        at etl.DatasetResolver$.byModel(DatasetResolver.scala:58)
        at etl.App$.processTask(App.scala:105)
        at etl.App$.main(App.scala:65)
        at etl.App.main(App.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)`

**Comment by nightscape** [comment] 2021-04-23 09:31
@sjahongir can you try the recommendation from @xvinosh?

**Comment by pjfanning** [comment] 2024-10-28 16:36
@neontty looks like Spark defaults to an out of date CVE ridden version of commons-compress.

https://mvnrepository.com/artifact/org.apache.spark/spark-core_2.13/3.5.3

POI uses a newer version of commons-compress and must rely on methods from that were added or changed recently.

Can you try to upgrade the commons-compress jar that Spark uses? Maybe best to ask on Spark mailing lists or forums if you don't know how to do this.

**Comment by neontty** [comment] 2024-11-11 21:29
hi @pjfanning , thanks for the quick response.  I'm just looking into this a bit more and trying to understand why the shading rule isn't enough in `build.sc:67` 

is it because of this discussion regarding shading in the mill build system? https://github.com/com-lihaoyi/mill/issues/3815

**Comment by nightscape** [comment] 2024-11-12 10:40
@neontty thanks for commenting over at Mill 👍 
If you and/or your colleagues could pick that issue up, that would be great.
With the bounty on top, you could do a nice celebration with your colleagues 🍻 😄
