### ISSUE TITLE
Reading multiple files

### ISSUE THREAD

**Issue by surtamikalai** [crealytics/spark-excel#97] opened 2018-11-29 08:59 UTC
It is no an issue, but I just don't know where is the best place to discuss project related question. Do you have in plans to add feature to read multiple xlsx files in directory, not only one at once? Spark supports doing it while working with .csv files by specifying wildcards/regexp. Then you "input_file_name()" function that returns column with source filename of every record.

**Comment by nightscape** [comment] 2018-11-29 10:04
Duplicate of https://github.com/crealytics/spark-excel/issues/74

**Closed by nightscape** 2018-11-29 10:04 UTC
