### ISSUE TITLE
maxRowsInMemory doesn't work with Spark-Excel V2 

### ISSUE THREAD

**Issue by mkrasilnikova** [crealytics/spark-excel#599] opened 2022-05-25 16:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have an excel file about 28 Mb size, which I can load perfectly with 
        Dataset<Row> dataset = sparkSession
                .read()
                .format("com.crealytics.spark.excel")
                .option("maxRowsInMemory", "200")
                .option("dataAddress", "'Sheet1'!B7:M16")
                .option("header", true)
                .option("inferSchema", true)
                .load("myFile.xlsx");

But if I switch to 
.format("excel") 
it just hangs. Is there any possibility to read big files in a streaming manner with data source API V2.0?

### Expected Behavior

I expect to be able to read the file in both formats
.format("com.crealytics.spark.excel") and .format("excel")

### Environment

```markdown
- Spark version: 3.2.0
- Spark-Excel version:0.14.0
```

**Comment by nightscape** [comment] 2022-05-27 19:07
Can you try with a newer version?

**Comment by mkrasilnikova** [comment] 2022-05-27 20:16
I have tried with 
- Spark version: 3.2.1
- Spark-Excel version:3.2.1_0.17.1

The same result.

**Comment by nightscape** [comment] 2022-05-30 12:18
@quanghgx are there any differences in how v2 handles `maxRowsInMemory`?

**Comment by christianknoepfle** [comment] 2022-06-06 09:54
Hi, I tried to reproduce it with some large xlsx file that I generated from test data (30MB, 60K rows). 
* Testcase [here](https://github.com/christianknoepfle/spark-excel/blob/75abbd090a2ceeb380664461389449209ac27ddc/src/test/scala/com/crealytics/spark/v2/excel/MaxNumRowsSuite.scala)
* Test data [here](https://github.com/christianknoepfle/spark-excel/blob/75abbd090a2ceeb380664461389449209ac27ddc/src/test/resources/v2readwritetest/large_excel/largefile.xlsx)

With that I could not reproduce the issue, so this is not a general issue and it it might be related to the xlsx file itself (or the transform you are doing with the dataframe). Are you able to provide data that demonstrates the issue ?

**Comment by mkrasilnikova** [comment] 2022-06-06 11:18
Hello! Here is the data [Test file](https://github.com/mkrasilnikova/testBigExcel/blob/main/data/giantFile.xlsx) and test program [example](https://github.com/mkrasilnikova/testBigExcel/blob/main/src/main/java/TestBigFile.java)
I can parse your file even without maxRowsInMemory option

**Comment by pjfanning** [comment] 2022-08-02 19:11
@nightscape @quanghgx the com.crealytics.spark.v2.excel package does not seem to use the excel-streaming-reader lib like the v1  datasource code does - so it seems the OP is correct, that the maxRowsInMemory is ignored when v2 datasource is used

**Comment by nightscape** [comment] 2022-08-20 00:39
Should be fixed in `0.17.2`. @mkrasilnikova could you give it a try and post your results here?
I'm closing this in the mean time.

**Closed by nightscape** 2022-08-20 00:39 UTC
