### ISSUE TITLE
Error while encoding: java.lang.RuntimeException: scala.Some is not a valid external type for schema of string

### ISSUE THREAD

**Issue by AmaniAyari** [crealytics/spark-excel#254] opened 2020-05-21 14:31 UTC
I am trying to load a file with one column only of type string (containing names of cities).

I am using the following code to read an excel file
```
public Dataset<org.apache.spark.sql.Row> load(String fileName) {
		Dataset<org.apache.spark.sql.Row> ret = null;
		try {
			logger.info("Reading file: ".concat(fileName));
			SparkSession spark = SparkFactory.createSession();
			DataFrameReader reader = spark.read().
					format("com.crealytics.spark.excel").
					option("useHeader", "true").
					option("treatEmptyValuesAsNulls", "true").
					option("inferSchema", "true").
					option("header", "true");
			if (schema == null) {
				reader = reader.option("inferSchema", "true");
			} else {
				reader = reader.schema(schema);
			}
			ret = reader.load(fileName);
		} catch (Exception e) {
			logger.error(e);
			throw e;
		} finally {

		}
		return ret;
	}
```
```
public void readFromExcel(){
		StructType schema = SparkUtils.createSchema(Arrays.asList(new String[][]{
			{"Ville", "string", "true"}						
		}));
		String fileName = "src/test/resources/data/excel/ville.xlsx";
		ExcelReader feed = new ExcelReader(fileName);
//		feed.setSchema(schema);
		Dataset<Row> data = feed.load();	
		data.show();
	}
```
When I call the display functionm it throws the following error

```
java.lang.RuntimeException: Error while encoding: java.lang.RuntimeException: scala.Some is not a valid external type for schema of string
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 0, Ville), StringType), true, false) AS Ville#5
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.toRow(ExpressionEncoder.scala:344)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.$anonfun$toCatalystRDD$2(DataSourceStrategy.scala:415)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:726)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:321)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:872)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:872)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:441)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:444)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: scala.Some is not a valid external type for schema of string
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.If_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.toRow(ExpressionEncoder.scala:340)
	... 19 more
```
Even when I add a schemam I still get the same error.

**Environment**
* Spark-sql_2.12 version 3.0.0-preview2
* Spark-Excel version: spark-excel_2.12 version 0.13.1
* Java 11 (OpenJDK)

Thank you
[ville.xlsx](https://github.com/crealytics/spark-excel/files/4662955/ville.xlsx)

**Comment by EnverOsmanov** [comment] 2020-05-21 15:50
Duplicate of #181. The fix is coming. You can try [this](https://github.com/crealytics/spark-excel/issues/181#issuecomment-629978828) solution for now.

**Closed by EnverOsmanov** 2020-05-21 15:50 UTC
