### ISSUE TITLE
cant read the whole excel file,if there 3 columns at first row,then read only 3 columns other all rows,that is a bug?or not

### ISSUE THREAD

**Issue by zochunphy** [crealytics/spark-excel#132] opened 2019-07-09 11:59 UTC
## code
       `SparkConf conf = new SparkConf();
        SparkSession sparkSession = SparkSession.builder()        
        .appName(Test.class).config(conf).enableHiveSupport().getOrCreate();
        JavaSparkContext sc = new JavaSparkContext(sparkSession.sparkContext());
       Dataset<Row> load = new SQLContext(sc).read().format("com.crealytics.spark.excel")
                        .option("useHeader", "false")
                        .option("location","hdfs://rousit/user/shf/50550000000005.xls")
                        .option("inferSchema","false")
                        .option("addColorColumns", "false")
                        .option("treatEmptyValuesAsNulls", "false")
                        .load();
            JavaRDD<Row> rowJavaRDD = load.toJavaRDD();
                 rowJavaRDD.foreachPartition(new VoidFunction<Iterator<Row>>() {
                @Override
                public void call(Iterator<Row> rowIterator) throws Exception {
                    while (rowIterator.hasNext()){
                        Row row = rowIterator.next();
                        System.out.println(">>>>>>>row"+row);
                    }
                }
            });
`
## Your Environment
> Include as many relevant details about the environment you experienced the bug in
* Spark version and language  spark-version：2.11  java/jdk1.7
* Spark-Excel version:0.8.3
    `
                  <dependency>
			<groupId>com.crealytics</groupId>
			<artifactId>spark-excel_2.11</artifactId>
			<version>0.8.3</version>
		</dependency>`
* Operating System and version, cluster environment, ...:

**Comment by nightscape** [comment] 2019-07-09 14:01
Please try a newer version. It makes no sense to support old versions.

**Comment by zochunphy** [comment] 2019-07-10 01:05
there throw Matcherror exception when i use 0.11.1 version
`Exception in thread "main" scala.MatchError: Map(treatemptyvaluesasnulls -> false, location -> hdfs://rousit/user/shf/50550000000005.xls, maxrowsinmemory -> 20, excerptsize -> 10, useheader -> true, timestampformat -> MM-dd-yyyy HH:mm:ss, endcolumn -> 99, inferschema -> false, startcolumn -> 0, addcolorcolumns -> false, sheetname -> Sheet1) (of class org.apache.spark.sql.catalyst.util.CaseInsensitiveMap)
	at com.crealytics.spark.excel.WorkbookReader$.apply(WorkbookReader.scala:30)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:28)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:18)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:12)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:330)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:152)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:125)
`

**Comment by zochunphy** [comment] 2019-07-10 02:33
spark-excel 0.10.2  only support xlsx file? xls file is not supported?

**Comment by nightscape** [comment] 2019-07-11 16:31
@zochunphy I guess you're using an old version of the call to spark-excel.
Can you please compare your call to the one in the README?

**Comment by wenyangchou** [comment] 2020-12-01 02:20
I met the same question, while I used the lastest version

**Comment by wenyangchou** [comment] 2020-12-01 02:21
val df = ss.read.format("com.crealytics.spark.excel")
      .option("header",value = false)
      .option("maxRowsInMemory",10000)
      .load("/Users/zhouwenyang/Desktop/test.xlsx")
    df.show(10)
It can only read the head and it can read all rows without .option("maxRowsInMemory",10000)

**Comment by nightscape** [comment] 2020-12-02 21:29
Hi @wenyangchou, what exactly is happening with `maxRowsInMemory`.
There might be problems with numbers as big as 10000.

**Comment by quanghgx** [comment] 2021-10-03 04:33
Hi @wenyangchou and @zochunphy ,

Is it possible if you two can share the excel files? We are trying to understand more about spark-excel resource usage (and its limitations) with the hope of addressing the root cause of this issue. 
Sincerely,

**Comment by quanghgx** [comment] 2022-01-15 12:38
Back to the original query, from the title:
```
cant read the whole excel file,if there 3 columns at first row,then read only 3 columns other all rows,that is a bug?or not
```
Spark-excel should be able to read only 3 columns for all remaining rows.

- If the header have only 3 columns, it should work out of the box
- If the header have more then 3 needed columns, or does not have header at all, spark-excel can accept custom schema (with 3 columns), and this also work

Hi @zochunphy and @wenyangchou, I am going to close this ticket, feel free to reopen it.

**Closed by quanghgx** 2022-01-15 12:38 UTC
Labels: large, need more detail
