### ISSUE TITLE
Handling Leading and Trailing Spaces in Sheet Names - manually generated excel sheets

### ISSUE THREAD

**Issue by rbharathkumar** [crealytics/spark-excel#469] opened 2021-11-30 07:21 UTC
Hi Team,
[Not a Bug]
We have loads of manually generated excel files (.xls) which we consume from within DBX.
We are facing issues reading sheets that have leading and trailing spaces in them.
We tried reading by providing the sheet number, but sometimes even the order gets changed.
We have also tried dynamic sheet names, but the sheet names are too similar to differentiate or we have to read only few of the sheets. These logics seem to be making the entire process complex than it needs to be.

Wanted to understand if there was any setting that could trim off the leading and trailing sheet names before reading the files.

## Expected Behavior
1. The sheet with leading or trailing spaces should be read. For example if the expected sheet name is "SHEET NAME" but the actual sheet name is " SHEET NAME ", the program should still be able to read it.
2.  If possible similar option can be given for case of the sheet name as well.

## Current Behavior
1. The notebook fails with below error message
`java.lang.IllegalArgumentException: Unknown sheet <SHEET_NAME>`

## Possible Solution
1. An option say `ignorespaceinsheetname` could be added.
2. This option could take 4 options say "Leading", "Trailing", "Both", "NA". 
3. NA would be the default option.

## Steps to Reproduce (for bugs)
1. Create a .xls file with the sheet name as ` SHEET NAME ` 
2. Note the leading and trailing spaces.
3. Read the file using the below snippet - Note that we are trying to read without the leading and trailing spaces.
```scala
df = spark.read
  .format("com.crealytics.spark.excel")
  .option("dataAddress", "'SHEET NAME'!A1") // Optional, default: "A1"
  .option("header", "true") // Required
  .option("treatEmptyValuesAsNulls", "true") // Optional, default: true
  .load(source_file_name_path)
```
## Context
Consuming manually generated excel sheets where the following cannot be guaranteed.
1. Sheet Names with no leading or trailing spaces.
2. Case of the Sheet names.
3. Order of the Sheets.

## Your Environment
Databricks Environment - LTS Run time

Spark version: 3.0.1
Language: Scala
Spark-Excel version: com.crealytics:spark-excel_2.12:0.13.7
Operating System and version, cluster environment, ...: Ubuntu - Databricks LTS runtime with sufficient memory and disk space.

**Comment by nightscape** [comment] 2021-11-30 13:03
Not sure if we would special-case this. Other people maybe want to read sheet names with a certain prefix or suffix.
Does the following approach from the README help?
```scala
val sheetNames = WorkbookReader( Map("path" -> "Worktime.xlsx")
                               , spark.sparkContext.hadoopConfiguration
                               ).sheetNames
val desiredSheetNames = sheetNames.map(_.trim).filter(_.startsWith("SHEET"))
val dfs = desiredSheetNames.map(sn =>
  spark.read.excel(
    header = true,
    dataAddress = sn
  )
)
```

**Comment by rbharathkumar** [comment] 2021-11-30 15:32
Thank you so much for your immediate response.
As I have mentioned, the logic to read the sheet names dynamically is something we have done for few of the sheets.
But the issue with manually generated excel files is that the sheet names are too similar.
e.g. we have had files with sheet names as Sheet1, Sheet2...and several others with spaces in between them as well...

The above mentioned logic would still work - but to do that repeatedly for each of the notebook is becoming a huge task by itself considering the number of excel files and sheets in them....
But I do agree - it works...

Regarding possible enhancement - this will not impact anybody since the default would be NA - meaning the existing functionality would continue to work. It would be enabled only to those who needed it...It could be useful to many dealing with such excel sheets...especially in cases where the number of sheets is high as well.

Thank you once again....

**Comment by quanghgx** [comment] 2022-01-10 17:09
Hi @rbharathkumar and @nightscape 

* In general, I do agree with Martin on the point of avoiding too specific processing on sheet-name.
* The best option, might be you build spark-excel fro**m source with your specific sheet-name patch?**
* Before closing this ticket, maybe we can do something generic about this.
   1. We can add a feature to return a list of sheet names through the data source interface. So it can be used by all spark-supported languages.
   2. And, by design, spark-excel V2 implementation is expected to work with multiple excel files at the same time, so the return can be combined with input_file_name as well.

For example:

```python
df = spark.read.format("excel")
.option("type", "SheetName")
.load(<path to folder contain excel files, glob is supported>)

df.show()
```

Result:
```bash
+--------------------+
|           SheetName|
+--------------------+
|              Sheet1|
|              Sheet2|
|              Sheet1|
+--------------------+
```

And combine with input_file_name
```python
df..withColumn("FileName", input_file_name()).show()
```
```bash
+--------------------+-------------------------+
|           SheetName|                 FileName|
+--------------------+-------------------------+
|              Sheet1|               data1.xlsx|
|              Sheet2|               data1.xlsx|
|              Sheet1|               data2.xlsx|
+--------------------+-------------------------+
```

**Closed by quanghgx** 2022-01-10 17:09 UTC
Labels: enhancement
