### ISSUE TITLE
py4j.protocol.Py4JJavaError: An error occurred while calling o638.save. : java.lang.RuntimeException: com.crealytics.spark.excel.DefaultSource does not allow create table as select.

### ISSUE THREAD

**Issue by subodh92** [crealytics/spark-excel#165] opened 2019-11-04 05:35 UTC
I am using latest version of com.crealytics:spark-excel_2.11:0.12.2 for writing excel file from pyspark data frame but I am getting the following exception.

My code is.

****df.write\**
  **.format("com.crealytics.spark.excel")\
  .option("dataAddress", "'data'!A1:Z1000000")\
  .option("useHeader", True)\
  .option("dateFormat", "yy-mmm-d")\
  .option("timestampFormat", "mm-dd-yyyy hh:mm:ss")\
  .mode("append")\
  .save("/home/subodh/Desktop/wor.xlsx"****

and exception like:
py4j.protocol.Py4JJavaError: An error occurred while calling o411.save.
: java.lang.RuntimeException: com.crealytics.spark.excel.DefaultSource does not allow create table as select.
	at scala.sys.package$.error(package.scala:27)
	at org.apache.spark.sql.execution.datasources.DataSource.planForWriting(DataSource.scala:526)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:290)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:229)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Please help me to solve this issue.
Thanks

**Comment by quanghgx** [comment] 2021-08-24 16:24
Hi @subodh92 

Cannot reproduce this issue. It Looks like it might come from some un-implemented method in the old spark-excel version. 
I did search around and only found this: https://issues.apache.org/jira/browse/SPARK-14525
So, I'm going to close this ticket.

It is already a long time ago, if you came back to this ticket, please take a try with the newer spark-excel version. There are examples with pyspark in [the wiki](https://github.com/crealytics/spark-excel/wiki) as well.

Feel free to reopen this ticket.

**Closed by quanghgx** 2021-08-24 16:24 UTC
