### ISSUE TITLE
Issue when the Header has only numbers

### ISSUE THREAD

**Issue by donthusa** [crealytics/spark-excel#117] opened 2019-03-19 20:51 UTC
I am using version 0.9.14. I cannot use any version above 0.9.14 due dependency mismatch

I have an excel sheet where the header is a number.
I get the following exception when reading: 
java.lang.IllegalStateException: Cannot get a STRING value from a NUMERIC cell

	at org.apache.poi.xssf.usermodel.XSSFCell.typeMismatch(XSSFCell.java:1077)
	at org.apache.poi.xssf.usermodel.XSSFCell.getRichStringCellValue(XSSFCell.java:395)
	at org.apache.poi.xssf.usermodel.XSSFCell.getStringCellValue(XSSFCell.java:347)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1$$anonfun$9.apply(ExcelRelation.scala:273)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1$$anonfun$9.apply(ExcelRelation.scala:272)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:272)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:269)
	at scala.Option.getOrElse(Option.scala:121)
	at com.crealytics.spark.excel.ExcelRelation.inferSchema(ExcelRelation.scala:269)
	at com.crealytics.spark.excel.ExcelRelation.<init>(ExcelRelation.scala:97)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:35)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:14)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:8)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:340)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:174)

**Comment by nightscape** [comment] 2019-03-24 21:15
Yes, we assume that headers are strings. You should be able to make sure they are by explicitly setting the cell format in Excel.

**Comment by donthusa** [comment] 2019-03-24 21:17
I tried setting the format on Excel to “Text” but it did not work. What else would you suggest?

**Comment by zochunphy** [comment] 2019-07-10 06:57
I have the same problem,the first row has number then throw error --"Cannot get a STRING value from a NUMERIC cell",
`SQLContext(sc).read().format("com.crealytics.spark.excel")
                    .option("addColorColumns", "false")
                    .option("treatEmptyValuesAsNulls", "false")
                    .option("useHeader", "false") // Required
                    .option("inferSchema", "true") // Optional, default: false
                    .option("skipFirstRows",startRow)// Optional, default: false
                    .option("path","2010678863.xlsx")
                    .load();`

**Comment by zochunphy** [comment] 2019-07-10 10:03
spark-excel version 0.10.2 
i suggest check the cellType of head cell value when read the header 

`private def inferSchema(): StructType = this.userSchema.getOrElse {
    val rawHeader = extractCells(excerpt.head).map {
     // maybe like this
      case Some(value) => getValueCheckType(value)
      case _ => ""
    }.toArray

    val dataTypes = if (this.inferSheetSchema) {
      val stringsAndCellTypes = excerpt.tail
        .map(r => extractCells(r).map(getSparkType))
      InferSchema(parallelize(stringsAndCellTypes))
    } else {
      // By default fields are assumed to be StringType
      val maxCellsPerRow =
        excerpt.map(_.cellIterator().asScala.size).reduce(math.max)
      (0 until maxCellsPerRow).map(_ => StringType: DataType).toArray
    }
    val fields = makeSafeHeader(rawHeader, dataTypes)
    val baseSchema = StructType(fields)
    if (addColorColumns) {
      fields.foldLeft(baseSchema) { (schema, header) =>
        schema.add(s"${header}_color", StringType, nullable = true)
      }
    } else {
      baseSchema
    }
  }
// maybe you can check type of value
 private def getValueCheckType(cellValue : Cell):String = {
    var cellType = cellValue.getCellType()
    if(cellType == CellType.STRING){
         return cellValue.getStringCellValue()
    }else if(cellType == CellType.NUMERIC){
         return cellValue.getNumericCellValue()
    }else if(cellType == CellType._NONE){
         return ""
    }
  }

`

**Comment by alexandrehpiva** [comment] 2021-11-05 14:56
Hi, I'm having the same problem with version 0.14.0: "Cannot get a STRING value from a NUMERIC cell" and the above java error. Any ideas?

**Comment by quanghgx** [comment] 2021-11-05 15:53
Hi @alexandrehpiva ,
Thanks for sharing the issue. Is it possible that you share your simplified excel file and steps to reproduce the issue?
Frankly, I did tried on my side and also review the code parts that can be related to the "STRING value from NUMERIC" in the header rows, however, I cannot reproduce it.
And if you have stack trace, please help share in this thread.
Sincerely,

**Comment by quanghgx** [comment] 2022-01-15 12:45
Hi @alexandrehpiva and @zochunphy 
Please use `spark.read.format("excel")` for V2 implementation. Numerical or undefined cell/cells in header row should not be an issue.
I am going to close this ticket, feel free to reopen it.

**Closed by quanghgx** 2022-01-15 12:45 UTC
Labels: need more detail
