### ISSUE TITLE
Excel writing error com.crealytics.spark.excel.DefaultSource does not allow create table as select

### ISSUE THREAD

**Issue by shashi4414** [crealytics/spark-excel#16] opened 2017-08-24 07:45 UTC
hi,
we are using com.crealytics.spark.excel in my java-spark project ,i working good but when i come to write the data an excel file i got error 
com.crealytics.spark.excel.DefaultSource does not allow create table as select.

 The will be  code use to write in excel file.
dataFileContent.write()
	  .format("com.crealytics.spark.excel")
	  .option("sheetName", "Daily")
	  .option("useHeader", "true")
	  .mode("overwrite")
	  .save("D:\\xls\\Book1.xlsx");

**Comment by nightscape** [comment] 2017-08-24 08:13
My first guess would be that you're not yet using `0.9.0`?

**Comment by shashi4414** [comment] 2017-08-28 07:26
thanks for the replay  nightscope .
we are using 0.9.0 version but  when we writing  got error like **"scala.MatchError: null****"** 

bellow is the code we are using to read and writing the file.
Reading File
Dataset<Row>	 df = sqlContext.read()
				    .format("com.crealytics.spark.excel")
				    .option("sheetName", "Sheet1") // Required
				    .option("useHeader", "true") // Required
				    .option("treatEmptyValuesAsNulls", "true") // Optional, default: true
				    .option("inferSchema", "false") // Optional, default: false
				    .option("addColorColumns", "false") // Optional, default: false
				    .option("startColumn", 0) // Optional, default: 0
				    .option("endColumn", 100) // Optional, default: Int.MaxValue
				    .load("D:\\xls\\demo.xlsx");
writing file. 
df.write()
	  .format("com.crealytics.spark.excel")
	  .option("useHeader", "true")
	  .save("D:\\xls\\excelWrite.xlsx"); 

Error
Exception in thread "main" scala.MatchError: null
	at com.crealytics.spark.excel.ExcelFileSaver.toCell(ExcelFileSaver.scala:28)
	at com.crealytics.spark.excel.ExcelFileSaver$$anonfun$2$$anonfun$apply$1.apply(ExcelFileSaver.scala:19)
	at com.crealytics.spark.excel.ExcelFileSaver$$anonfun$2$$anonfun$apply$1.apply(ExcelFileSaver.scala:19)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.crealytics.spark.excel.ExcelFileSaver$$anonfun$2.apply(ExcelFileSaver.scala:19)
	at com.crealytics.spark.excel.ExcelFileSaver$$anonfun$2.apply(ExcelFileSaver.scala:18)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:370)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:183)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:308)
	at scala.collection.AbstractIterator.to(Iterator.scala:1194)
	at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:292)
	at scala.collection.AbstractIterator.toList(Iterator.scala:1194)
	at com.crealytics.spark.excel.ExcelFileSaver.save(ExcelFileSaver.scala:20)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:71)
	at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:426)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:215)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:198)
	at com.unilog.recordlinkage.action.HadoopOffice.main.

**Comment by nightscape** [comment] 2017-08-28 09:18
Ok, the `toCell` method does not actually handle `null`s: https://github.com/crealytics/spark-excel/blob/master/src/main/scala/com/crealytics/spark/excel/ExcelFileSaver.scala#L28-L40
Would you mind creating a PR that does this?

**Comment by shashi4414** [comment] 2017-08-29 12:56
ok,
so  ho can i handle  this issue.
please help me

**Comment by nightscape** [comment] 2017-08-29 14:32
If you dare to create a PR, that would be the best option and I would try to release a new version very soon.
If you don't, you can work around that issue by making sure that no column contains `null` values.
Third option is that you wait until we do the next round of improvements on this plugin and fix the issue.

**Comment by nightscape** [comment] 2017-09-04 08:23
Closing this as duplicate of #18 which has a better description of the `null` problem.

**Closed by nightscape** 2017-09-04 08:23 UTC
