### ISSUE TITLE
Is it possible to write multiple dataframes to different sheets in the same Excel worksheet

### ISSUE THREAD

**Issue by calvinlfer** [crealytics/spark-excel#68] opened 2018-05-17 21:23 UTC
I have a case where I have multiple DataFrames and each DataFrame maps to a sheet in the Excel document. Is it possible to do this? It seems like this needs to support the `append` write mode for this to work.

**Comment by nightscape** [comment] 2018-05-18 09:49
Sounds like a duplicate of https://github.com/crealytics/spark-excel/issues/43.
Maybe you can post a little more information over there.
We won't be able to implement this time-wise, but maybe someone comes up with a PR 😄

**Closed by nightscape** 2018-05-18 09:49 UTC
